### ISSUE TITLE
Fork length vs. Fork crown height - Nonstandard scheme?

### ISSUE THREAD

**Issue by vucalur** [Yellow-Me/bikegeo#1]
I believe that what you have defined as _fork length_ (No. 3 on [the scheme](https://github.com/Yellow-Me/bikegeo/blob/master/help.png)) is called [_fork crown height_](https://thumbor-static.factorymedia.com/JenfMstWjUh-UOnldRLd0vlnNqw=/1084x548/smart/http%3A%2F%2Fcoresites-cdn.factorymedia.com%2Frcuk%2Fwp-content%2Fuploads%2F2016%2F11%2Fmason-geometry.jpg) instead.

source: [Road Cycling UK, _Beginner’s guide: how to make sense of a bike geometry chart_](https://roadcyclinguk.com/gear/beginners-guide-make-sense-bike-geometry-chart.html)

**Comment by Yellow-Me** [comment]
"fork length" is also widely used, for example: https://www.sheldonbrown.com/rinard/forklengths.htm and https://www.bikecad.ca/fork_length

**Comment by vucalur** [comment]
In geometry specifications of modern road bikes, fork length, not crown height is more likely to be listed (usu. 370mm).
But of course the decision is up to you.
